version: '3.8'

services:
  water_web:
    container_name: water_web
    build:
      context: ../
      dockerfile: docker/backend_docker/Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - water_postgres
      - water_redis
    env_file:
      - ./.env
    volumes:
      - ../backend:/app
      - ../frontend:/usr/share/nginx/html
      - ../backend/media:/app/media   # mount media folder
    networks:
      - water_management_net

  water_postgres:
    image: postgres:latest
    container_name: water_postgres
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - water_management_net

  water_redis:
    image: redis:latest
    container_name: water_redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - water_management_net

  water_celery_worker:
    container_name: water_celery_worker
    build:
      context: ../
      dockerfile: docker/backend_docker/Dockerfile
    command: celery -A water_website worker -l info
    volumes:
      - ../backend:/app
    env_file:
      - ./.env
    depends_on:
      - water_web
      - water_redis
    networks:
      - water_management_net

  water_celery_beat:
    container_name: water_celery_beat
    build:
      context: ../
      dockerfile: docker/backend_docker/Dockerfile
    command: celery -A water_website beat -l info
    volumes:
      - ../backend:/app
    env_file:
      - ./.env
    depends_on:
      - water_web
      - water_redis
    networks:
      - water_management_net

  water_nginx:
    container_name: water_nginx
    build:
      context: ../../
      dockerfile: src/docker/nginx/Dockerfile
    volumes:
      - ../frontend:/usr/share/nginx/html
      - ../backend/media:/usr/share/nginx/html/media   # serve media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - water_web
    restart: on-failure
    networks:
      - water_management_net

volumes:
  postgres_data:
  redis_data:

networks:
  water_management_net:
    driver: bridge
